# Generated by Django 5.1.3 on 2024-12-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True, help_text="Укажите Вашу страну", max_length=30, null=True, verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/", verbose_name="Аватар"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                help_text="Введите номер телефона", max_length=254, unique=True, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="Введите номер телефона", max_length=15, null=True, verbose_name="Телефон"
            ),
        ),
    ]
