# Generated by Django 5.1.3 on 2024-12-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_country_alter_customuser_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(help_text="Введите Email", max_length=254, unique=True, verbose_name="Телефон"),
        ),
    ]
