# Generated by Django 5.1.3 on 2024-12-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(help_text="Введите Email", max_length=254, unique=True, verbose_name="Email"),
        ),
    ]
