# Generated by Django 5.1.3 on 2024-12-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                (
                    "content",
                    models.TextField(blank=True, default="Описание отсутствует", null=True, verbose_name="Содержимое"),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="", verbose_name="Изображение")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_active", models.BooleanField(default=True, verbose_name="Признак публикации")),
                ("counted_views", models.PositiveIntegerField(verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
