# Generated by Django 5.1.3 on 2024-12-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="counted_views",
            field=models.PositiveIntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
