# Generated by Django 5.1.3 on 2024-12-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_description_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(
                blank=True, default="Описание отсутствует", max_length=300, null=True, verbose_name="Описание"
            ),
        ),
    ]
