# Generated by Django 5.1.3 on 2024-12-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default="Описание отсутствует", null=True, verbose_name="Описание"),
        ),
    ]
